version: '3.7'
services:
  glpi:
    image: diouxx/glpi
    container_name: glpi
    ports:
      - "80:80"
    environment:
      - MYSQL_ROOT_PASSWORD=Adm3Pl2
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpiuser
      - MYSQL_PASSWORD=password1
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: glpi-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Adm3Pl2
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpiuser
      - MYSQL_PASSWORD=password1
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

