---
- name: Deploy GLPI and MySQL using Docker Compose
  hosts: dockerx
  become: true
  tasks:
    - name: Copy docker-compose.yml file
      copy:
        src: docker-compose.yml
        dest: $PWD/docker-compose.yml

    - name: Deploy services using Docker Compose
      command: cd /home/vagrant/ && docker-compose up -d


